version: '3.4'
# former url for reverse proxy http://10.0.0.4:19081/lil/employee/
services:
  appraisal:
    image : okoyeapps/resourceedgeappraisalapi:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Services__employee=http://lil/employee/
      - DefualtConnection__ConnectionString=mongodb+srv://chocksy:ewZg5URqMNyal7Xs@lawyerpp-cluster-5faak.mongodb.net/EdgeAppraisal?retryWrites=true
      - DefualtConnection__DataBaseName=EdgeAppraisal
    ports:
      - "6001:80"

  authentication:
    image: okoyeapps/resourceedgeauthenticationapi:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80/http"


  employee:
    image: okoyeapps/resourceedgeemployeeapi:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DefualtConnection__ConnectionString=mongodb+srv://chocksy:ewZg5URqMNyal7Xs@lawyerpp-cluster-5faak.mongodb.net/EdgeEmployee?retryWrites=true
      - DefualtConnection__DataBaseName=EdgeEmployee
    ports:
      - "80/http"
