version: '3.4'

services:
  appraisal:
    image : okoyeapps/resourceedgeappraisalapi:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__employee=http://10.0.0.4:19081/lil/employee/
      - DefualtConnection__ConnectionString=mongodb+srv://chocksy:ewZg5URqMNyal7Xs@lawyerpp-cluster-5faak.mongodb.net/EdgeAppraisal?retryWrites=true
      - DefualtConnection__DataBaseName=EdgeAppraisal
    ports:
      - "6001:80"

  authentication:
    image: okoyeapps/resourceedgeauthenticationapi:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"


  employee:
    image: okoyeapps/resourceedgeemployeeapi:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - DefualtConnection__ConnectionString=mongodb+srv://chocksy:ewZg5URqMNyal7Xs@lawyerpp-cluster-5faak.mongodb.net/EdgeEmployee?retryWrites=true
      - DefualtConnection__DataBaseName=EdgeEmployee
    ports:
      - "80/http"
      - "443/Https"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
      - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro
