version: '3.4'

services:
  resourceedge.appraisal.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
     # - DefaultConnection__ConnectionString=mongodb+srv://emma:%40A1234567@lawyerpp-cluster-5faak.mongodb.net/EdgeAppraisal?retryWrites=true&w=majority
      - DefaultConnection__ConnectionString=mongodb+srv://edgeadmin:9o2oNXbr9kmuDrwI@version1cluster-j74f5.mongodb.net/EdgeAppraisal?retryWrites=true&w=majority
      - DefaultConnection__DataBaseName=EdgeAppraisal
      - Services__employee=https://resourceedgeemployee.azurewebsites.net/api
      - SendGrid__SENDGRID_API_KEY=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
    ports:
      - "6001:80"
      
  resourceedge.authentication.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "7001:80"
      - "7000:443"

  resourceedge.employee.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DefaultConnection__ConnectionString=mongodb+srv://edgeadmin:9o2oNXbr9kmuDrwI@version1cluster-j74f5.mongodb.net/EdgeEmployee?retryWrites=true&w=majority
      - DefaultConnection__DataBaseName=EdgeEmployee
      - SendGrid__SENDGRID_API_KEY=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
    ports:
      - "8001:80"