version: '3.4'

services:
  resourceedge.appraisal.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__employee=http://resourceedge.employee.api
      - DefualtConnection__ConnectionString=mongodb+srv://chocksy:ewZg5URqMNyal7Xs@lawyerpp-cluster-5faak.mongodb.net/EdgeAppraisal?retryWrites=true
      - DefualtConnection__DataBaseName=EdgeAppraisal
    ports:
      - "6001:80"

  resourceedge.authentication.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6002:80"


  resourceedge.employee.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - DefualtConnection__ConnectionString=mongodb+srv://chocksy:ewZg5URqMNyal7Xs@lawyerpp-cluster-5faak.mongodb.net/EdgeEmployee?retryWrites=true
      - DefualtConnection__DataBaseName=EdgeEmployee
    ports:
      - "6003:80"
      - "7003:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
      - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro
